question_data = [
    {"category": "Animals", "type": "boolean", "difficulty": "easy", "question": "A slug&rsquo;s blood is green.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium",
     "question": "The flag of South Africa features 7 colours.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "DragonForce&#039;s &#039;Through the Fire and Flames&#039; is widely considered to be the hardest song in the Guitar Hero series.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "The film &quot;2001: A Space Odyssey&quot; was released on December 31st, 2000.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
     "question": "The M41 Walker Bulldog remains in service in some countries to this day.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                       "question": "The word &quot;Inception&quot; came from the 2010 blockbuster hit &quot;Inception&quot;.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Furby was released in 1998.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "easy",
     "question": "The United States was a member of the League of Nations.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In Kingdom Hearts the Paopu fruit is said to intertwine the destinies for two people forever.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In &quot;Sonic Adventure&quot;, you are able to transform into Super Sonic at will after completing the main story.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In &quot;Team Fortress 2&quot;, the &quot;Bill&#039;s Hat&quot; is a reference to the game &quot;Dota 2&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "Solid Snake is actually a clone from the DNA of Big Boss in the Metal Gear Solid series&#039; history.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "In the &quot;Melancholy of Haruhi Suzumiya&quot; series, the narrator goes by the nickname Kyon.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "medium",
     "question": "The anime Attack on Titan was directed by Tetsur\u014d Araki, the same person who directed the anime Highschool of the Dead.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
     "question": "Stephen Chbosky wrote the book &#039;The Perks of Being A Wallflower&#039;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
     "question": "Throughout the entirety of &quot;Dragon Ball Z&quot;, Goku only kills two characters: a miniboss named Yakon and Kid Buu.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "When you cry in space, your tears stick to your face.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                       "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "hard",
     "question": "Switzerland has four national languages, English being one of them.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In Pok&eacute;mon Sun and Moon, a male Salandit can evolve to a Salazzle.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "An exothermic reaction is a chemical reaction that releases energy by radiating electricity.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium",
     "question": "Liechtenstein does not have an airport.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
     "question": "The General Motors EV1 was the first street-legal production electric vehicle.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "hard",
     "question": "The band STRFKR was also briefly known as Pyramiddd.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy", "question": "Cats have whiskers under their legs.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In Riot Games &quot;League of Legends&quot; the name of Halloween event is called &quot;The Reckoning&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
     "question": "Adolf Hitler was accepted into the Vienna Academy of Fine Arts.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "Android versions are named in alphabetical order.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Sports", "type": "boolean", "difficulty": "easy",
     "question": "In Rugby League, performing a &quot;40-20&quot; is punished by a free kick for the opposing team.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "hard",
     "question": "The weapon Clint Eastwood uses in &quot;Dirty Harry&quot; was a .44 Automag.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "New Haven is the capital city of the state of Connecticut in the United States.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "Musical artist, Future, collaborated with Kendrick Lamar for the song: &quot;Mask Off&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "The scrapped Sonic the Hedgehog 2 level &quot;Hidden Palace Zone&quot; was later reused in the iOS port of the game. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In the &quot;S.T.A.L.K.E.R.&quot; series, the Freedom faction wishes to destroy the supernatural area known as  &quot;the Zone&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Mythology", "type": "boolean", "difficulty": "hard",
     "question": "Janus was the Roman god of doorways and passageways.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
                                       "question": "Rabbits can see what&#039;s behind themselves without turning their heads.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
     "question": "A scalene triangle has two sides of equal length.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Animals", "type": "boolean", "difficulty": "medium",
                                      "question": "You can tell the age of a ladybird by counting the spots on his back.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The British organisation CAMRA stands for The Campaign for Real Ale.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                       "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Art", "type": "boolean", "difficulty": "hard",
     "question": "The Statue of Liberty&#039;s official name is &ldquo;Liberty Enlightening the World&rdquo;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "Shang Tsung is a playable character in Mortal Kombat XL.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "hard",
                                      "question": "Only one country in the world starts with the letter Q.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "Minecraft wasn&rsquo;t the original name to Minecraft.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                       "question": "Lead Singer Rivers Cuomo of American rock band Weezer attended Harvard.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "Green Day&#039;s album &#039;American Idiot&#039; is considered a &quot;punk rock opera.&quot;",
     "correct_answer": "True", "incorrect_answers": ["False"]}
]
